# Generated by Django 6.0.6 on 2026-06-08 15:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


BLOCKING_REASONS = [
    (
        "a7b8c9d0-1234-5678-ef01-890123456789",
        "Описание не соответствует товару",
        False,
    ),
    (
        "b8c9d0e1-2345-6789-f012-901234567890",
        "Изображение не соответствует товару",
        False,
    ),
    (
        "c9d0e1f2-3456-7890-0123-012345678901",
        "Некорректная категория товара",
        False,
    ),
    (
        "d0e1f2a3-4567-8901-1234-123456789012",
        "Недостаточно информации о товаре",
        False,
    ),
    (
        "e1f2a3b4-5678-9012-2345-234567890123",
        "Нецензурные или оскорбительные материалы",
        False,
    ),
    (
        "f2a3b4c5-6789-0123-3456-345678901234",
        "Дублирование существующего товара",
        False,
    ),
    (
        "a3b4c5d6-7890-1234-4567-456789012345",
        "Некорректная цена",
        False,
    ),
    (
        "b4c5d6e7-8901-2345-5678-567890123456",
        "Контрафактный товар",
        True,
    ),
    (
        "c5d6e7f8-9012-3456-6789-678901234567",
        "Товар запрещён к продаже на территории РФ",
        True,
    ),
    (
        "d6e7f8a9-0123-4567-7890-789012345678",
        "Товар нарушает авторские права",
        True,
    ),
]


def seed_blocking_reasons(apps, schema_editor):
    product_blocking_reason = apps.get_model(
        "product_moderation", "ProductBlockingReason"
    )
    product_blocking_reason.objects.bulk_create(
        [
            product_blocking_reason(
                id=uuid.UUID(reason_id),
                title=title,
                hard_block=hard_block,
            )
            for reason_id, title, hard_block in BLOCKING_REASONS
        ],
        ignore_conflicts=True,
    )


def remove_blocking_reasons(apps, schema_editor):
    product_blocking_reason = apps.get_model(
        "product_moderation", "ProductBlockingReason"
    )
    product_blocking_reason.objects.filter(
        id__in=[uuid.UUID(reason_id) for reason_id, _, _ in BLOCKING_REASONS]
    ).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductBlockingReason",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("hard_block", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "product_blocking_reasons",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ProductModeration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.UUIDField(unique=True)),
                ("seller_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_REVIEW", "In review"),
                            ("MODERATED", "Moderated"),
                            ("BLOCKED", "Blocked"),
                            ("HARD_BLOCKED", "Hard blocked"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("queue_priority", models.PositiveSmallIntegerField()),
                ("total_active_quantity", models.PositiveIntegerField(default=0)),
                ("json_before", models.JSONField(blank=True, null=True)),
                ("json_after", models.JSONField()),
                ("moderator_id", models.UUIDField(blank=True, null=True)),
                ("moderator_comment", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_moderation", models.DateTimeField(blank=True, null=True)),
                (
                    "blocking_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_moderations",
                        to="product_moderation.productblockingreason",
                    ),
                ),
            ],
            options={
                "db_table": "product_moderation",
                "ordering": ["queue_priority", "date_updated"],
            },
        ),
        migrations.CreateModel(
            name="ProductModerationFieldReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        choices=[
                            ("title", "Title"),
                            ("description", "Description"),
                            ("product_images", "Product images"),
                            ("category", "Category"),
                            ("sku_name", "SKU name"),
                            ("sku_image", "SKU image"),
                            ("sku_price", "SKU price"),
                        ],
                        max_length=32,
                    ),
                ),
                ("sku_id", models.UUIDField(blank=True, null=True)),
                ("comment", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "product_moderation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_reports",
                        to="product_moderation.productmoderation",
                    ),
                ),
            ],
            options={
                "db_table": "product_moderation_field_report",
                "ordering": ["date_created"],
            },
        ),
        migrations.AddIndex(
            model_name="productmoderation",
            index=models.Index(
                fields=["status", "queue_priority", "date_updated"],
                name="product_mod_status_3c67ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productmoderation",
            index=models.Index(
                fields=["seller_id"], name="product_mod_seller__92a840_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productmoderation",
            index=models.Index(
                fields=["moderator_id"], name="product_mod_moderat_07d645_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productmoderation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("queue_priority__gte", 1), ("queue_priority__lte", 4)
                ),
                name="product_moderation_queue_priority_1_4",
            ),
        ),
        migrations.AddIndex(
            model_name="productmoderationfieldreport",
            index=models.Index(
                fields=["product_moderation", "field_name"],
                name="product_mod_product_10ad38_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productmoderationfieldreport",
            index=models.Index(fields=["sku_id"], name="product_mod_sku_id_97a03e_idx"),
        ),
        migrations.RunPython(seed_blocking_reasons, remove_blocking_reasons),
    ]
