# Generated by Django 6.0.6 on 2026-06-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_moderation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmoderation",
            name="queue_priority",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "New products"),
                    (2, "Fixed after block"),
                    (3, "Edited in stock"),
                    (4, "Edited out of stock"),
                ]
            ),
        ),
        migrations.AddIndex(
            model_name="productmoderation",
            index=models.Index(
                condition=models.Q(
                    ("date_moderation__isnull", True), ("status", "PENDING")
                ),
                fields=["date_updated"],
                name="pm_queue_new_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productmoderation",
            index=models.Index(
                condition=models.Q(
                    ("blocking_reason__isnull", False),
                    ("date_moderation__isnull", False),
                    ("status", "PENDING"),
                ),
                fields=["date_updated"],
                name="pm_queue_fixed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productmoderation",
            index=models.Index(
                condition=models.Q(
                    ("blocking_reason__isnull", True),
                    ("date_moderation__isnull", False),
                    ("status", "PENDING"),
                    ("total_active_quantity__gt", 0),
                ),
                fields=["date_updated"],
                name="pm_queue_stock_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productmoderation",
            index=models.Index(
                condition=models.Q(
                    ("blocking_reason__isnull", True),
                    ("date_moderation__isnull", False),
                    ("status", "PENDING"),
                    ("total_active_quantity", 0),
                ),
                fields=["date_updated"],
                name="pm_queue_no_stock_idx",
            ),
        ),
    ]
